export default speakersData = {
    "speakers_track_1":[
        {
            "id": 1,
            "name":"Ana Cristina Perez Benedí",
            "avatar":"upload/AnaCristinaPerez.jpg",
            "talk_tile":"Las matemáticas de la vida. Fractales.",
            "talk_short_description":"Ana Cristina Pérez Benedí nos hablará de la íntima relación entre las matemáticas y el mundo que nos rodea a través de los fractales.",
            "talk_long_description":"<p>Situándome históricamente en los descubrimientos de dos grandes matématicos, reúno los avances tecnológicos conseguidos en Programación para mostrar todo un universo entorno a la Geometría fractal.</p><p>Los fractales, están presentes en muchas estructuras naturales como por ejemplo las nubes, las montañas, el sistema circulatorio, las líneas costeras o los copos de nieve.</p><p>Además aparecen en otros ámbitos de la vida como el Arte, la Medicina y el Big Data.</p>",
            "talk_time_scheduled":"xx:xx - xx:xx",
            "social_media_link":null,
            "professional_profile_link":null,
            "isLinkedin":false,
            "professional_title":"Licenciada en Matemáticas y docente de desarrollo web en Jesuitas Logroño"
        },
        {
            "id": 2,
            "name":"Miriam García Toledo",
            "avatar":"upload/MiriamGarcia.jpg",
            "talk_tile":"Simplifica para crecer: Flat Design",
            "talk_short_description":"Miriam García Toledo nos mostrará la magia del diseño más actual con Flat Design",
            "talk_long_description":"<p>Un viaje por la historia del Flat Design o 'diseño plano' en el que veremos qué es y por qué querremos utilizarlo para crecer.</p><p>¡Úsalo en tu propio beneficio!</p>",
            "talk_time_scheduled":"xx:xx - xx:xx",
            "social_media_link":"https://twitter.com/miriamgarciatol",
            "professional_profile_link":"https://www.linkedin.com/in/miriam-garc%C3%ADa-toledo-6255499a/",
            "isLinkedin": true,
            "professional_title":"Diseñadora Gráfica y Diseñadora WEB en SDi Digital Group"
        },
        {
            "id": 3,
            "name":"Marta García Luis",
            "avatar":"upload/MartaGarciaLuis.jpg",
            "talk_tile":"La moneda cuántica",
            "talk_short_description":"Marta García Luis nos acercará al mundo de la criptografía y la computación cuántica",
            "talk_long_description":"<p>Mucho se habla de la computación cuántica, pero ¿Cuando y como surgió esta idea? ¿Qué papel juega la criptografía? ¿Qué es la moneda cuántica? </p><p>En esta charla resolveremos juntos estas incógnitas.</p>",
            "talk_time_scheduled":"xx:xx - xx:xx",
            "social_media_link":"https://twitter.com/martadosptocero",
            "professional_profile_link":"https://www.linkedin.com/in/martagarcialuis/",
            "isLinkedin": true,
            "professional_title":"Ingeniera Informática, especializada en criptografía y computación cuántica"
        },
        {
            "id": 4,
            "name":"Victor Sánchez Belmar",
            "avatar":"upload/VictorSanchezBelmar.jpg",
            "talk_tile":"Empezando con webcomponents",
            "talk_short_description":"Victor Sánchez Belmar nos enseñará todo lo que necesitamos saber para crear nuestros propios web components",
            "talk_long_description":"<p>En esta sesión aprenderemos lo que son los web components y porqué son importantes para el futuro de una web ligera, estándar y pragmática.</p><p>Exploraremos juntos lit-html y lit-element viendo cómo crear nuestros primeros componentes juntos usado esta tecnología apoyada por Google.</p><p>Usaremos las recomendaciones y generadores disponibles en open-wc.org!</p>",
            "talk_time_scheduled":"xx:xx - xx:xx",
            "social_media_link":"https://twitter.com/VictorSanchez",
            "professional_profile_link":null,
            "isLinkedin": false,
            "professional_title":"Google Developer Expert en HTML5 y CEO de <a href=\"https://www.mashme.io\">Mashme.io</a>"
        },
        {
            "id": 5,
            "name":"Nicolás Patarino",
            "avatar":"upload/NicolasPatarino.jpeg",
            "talk_tile":"Dime que me quieres.",
            "talk_short_description":"Nicolás Patarino nos explicará cómo debemos (y cómo no) dar feedback, ¡y recibirlo!",
            "talk_long_description":"<p>Aunque no seamos conscientes nos pasamos el día entero dando feedback, tanto en nuestro entorno técnico como personal, desde code reviews hasta una conversación informal con tu jefa o jefe en el café, pasando por reviews de productos o entrevistas de trabajo.</p><p>Cuanto más feedback recibamos mejores personas y profesionales podremos llegar a ser, pero, pero, pero, ¿sabemos dar buen feedback?, o mejor aún, ¿debemos dar buen feedback? </p><p>En esta sesión analizaremos las claves para dar y recibir feedback, asimilar y trabajar en ese feedback, analizar y detectar si debemos cambiar nuestra actitud o no.</p>",
            "talk_time_scheduled":"xx:xx - xx:xx",
            "social_media_link":"https://www.twitter.com/npatarino",
            "professional_profile_link":"http://linkedin.com/in/npatarino",
            "isLinkedin": true,
            "professional_title":"Porteño \"barrabrava\" de Android y Kotlin, Principal Android Engineer en Tymit"
        },
        {
            "id": 6,
            "name":"Raul Portales Fernandez",
            "avatar":"upload/RaulPortales.jpg",
            "talk_tile":"Neurodiversidad",
            "talk_short_description":"Raul Portales Fernandeznos hablará de la neurodiversidad y de los beneficios que ésta puede aportar en el entorno laboral",
            "talk_long_description":"<p>La Neurodiversidad es un concepto que se basa en que las diferencias neurológicas deben ser reconocidas y respetadas como cualquier otro tipo de variación en el ser humano.El término se usa mayormente para referirse a Autismo (TEA) e Hiperactividad / falta de atención (TDAH).</p><p>En esta charla nos centraremos en el Autismo, dando una breve introducción para explorar los beneficios que aporta la neurodiversidad en general y en el entorno de trabajo en particular y cómo puedes empezar a marcar la diferencia hoy mismo.</p><p>Todos sabemos que la diversidad es importante, pero es muy fácil pasar por alto la neurodiversidad, ya que es invisible.</p>",
            "talk_time_scheduled":"xx:xx - xx:xx",
            "social_media_link":"https://www.twitter.com/sla_shalafi",
            "professional_profile_link":"https://www.linkedin.com/in/raulportales/",
            "isLinkedin": true,
            "professional_title":"Senior Software Development Engineer en Workday (Dublín)"
        },
        {
            "id": 7,
            "name":"Luis Marqueta",
            "avatar":"upload/LuisMarqueta.jpg",
            "talk_tile":"Seguridad en el proceso de Desarrollo",
            "talk_short_description":"Luis Marqueta nos mostrará cómo contar con la seguridad del software de tu proyecto desde el día 1.",
            "talk_long_description":"<p>Es más barato hacer software seguro que arreglarlo después de un incidente; para ello, nada mejor que incorporar la seguridad desde el principio del proyecto. </p><p>Del \"¡ay, hazme un pentesting que salimos mañana a producción!\" a la integración de la seguridad en las metodologías ágiles.</p>",
            "talk_time_scheduled":"xx:xx - xx:xx",
            "social_media_link":null,
            "professional_profile_link":null,
            "isLinkedin": false,
            "professional_title":"Administrador de sistemas en Arsys y experto en seguridad."
        },
        {
            "id": 8,
            "name":"Adrián Bolonio",
            "avatar":"upload/AdrianBolonio.jpg",
            "talk_tile":"Testeando Accesibilidad Web",
            "talk_short_description":"Adrián Bolonio nos explicará cómo tener presente la Accesibilidad Web cuando desarrollamos.",
            "talk_long_description":"<p>Cuando desarrollamos una nueva web, a menudo ponemos mucho trabajo en el diseño, para que sea bonita y utilizable. En otras palabras, queremos que nuestra web sea efectiva, eficiente y satisfactoria para el usuario. Pero muchas veces no pensamos en la experiencia del usuario para las personas con discapacidades, incluidas las personas con discapacidades relacionadas con la edad.</p><p>Accesibilidad web (a11y) significa que las personas con discapacidad pueden percibir, comprender, navegar e interactuar con sitios web y herramientas, y que pueden contribuir igualmente sin barreras ”. (Fuente: W3C - Web Accessibility Initiative). Nuestro papel como desarrolladores frontend es crear interfaces claras para que las personas entiendan y se preocupen por los datos, independientemente de sus discapacidades o impedimentos, pero lo que nosotros, los desarrolladores, a menudo olvidamos es asegurarnos de que el código que escribimos siga las \"Web Content Accessibility Guidelines\" (WCAG), y la única forma de lograrlo es mediante test, ya sea manuales o automatizados.</p><p>Los tests automatizados de accesibilidad web pueden liberar a nuestro equipo de QA de los tests manuales de cada parte de nuestra aplicación, pero, no pueden hacer que nuestro sitio sea accesible de forma automática y mágica.</p><p>Deberíamos usar tests automatizados de accesibilidad web como un paso de un proceso de tests más grande. No olvidemos que solo se puede detectar automáticamente del 20% al 50% de todos los problemas de accesibilidad.</p><p>Enseñaré algunas herramientas de tests, bibliotecas y técnicas para aumentar la cobertura de tests de tu código con un simple ejemplo con una aplicación React. </p>",
            "talk_time_scheduled":"xx:xx - xx:xx",
            "social_media_link":"https://twitter.com/bolonio",
            "professional_profile_link":"https://www.adrianbolonio.com/es",
            "isLinkedin": false,
            "professional_title":"Engineering Team Lead, Senior Frontend Developer, y gran defensor de la Accesibilidad Web."
        },
        {
            "id": 9,
            "name":"Javier Menendez Pallo",
            "avatar":"upload/JavierMenendez.jpg",
            "talk_tile":"Computer Vision: Exposed!",
            "talk_short_description":"Javier Menendez Pallo nos contará todo lo que hay detrás del software de reconocimiento de imágenes más novedoso de Microsoft",
            "talk_long_description":"<p>Si, ya lo sabemos, esto lo tenemos super-controlado verdad? Va de reconocer caras y todo eso no? </p><p>Pues nada más alejado de la realidad, te traemos lo último de uno de los servicios estrella del AI de Microsoft, donde no solo vas a ver como puedes averiguar lo que hay en una imagen (sean o no personas) sino que podrás ver el OCR en acción, el reconocimiento de caracteres o incluso reconocer marcas, logos, personas conocidas. </p><p>Te vas a sorprender de lo que somos (tú incluido) con una imagen. </p>",
            "talk_time_scheduled":"xx:xx - xx:xx",
            "social_media_link":"https://www.twitter.com/JavierPallo",
            "professional_profile_link":"https://www.linkedin.com/in/jamepa/",
            "isLinkedin": true,
            "professional_title":"Microsoft AI MVP y Doctor en Inteligencia Artificial (PhD)"
        }
    ]
}